locate topology st.st at "./st.fpp"
locate topology main.main at "./main.fpp"
locate instance st.a at "./st.fpp"
locate instance st.b at "./st.fpp"
locate instance st.c at "./st.fpp"
locate instance main.main_a at "./main.fpp"
locate instance main.b at "./main.fpp"
locate instance main.main_c at "./main.fpp"