locate topology st.st at "../example/fpp-src/st.fpp"
locate topology main.main at "../example/fpp-src/main.fpp"
locate instance st.a at "../example/fpp-src/st.fpp"
locate instance st.b at "../example/fpp-src/st.fpp"
locate instance st.c at "../example/fpp-src/st.fpp"
locate instance main.main_a at "../example/fpp-src/main.fpp"
locate instance main.b at "../example/fpp-src/main.fpp"
locate instance main.main_c at "../example/fpp-src/main.fpp"