locate topology st.st at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/st.fpp"
locate topology main.main at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/main.fpp"
locate instance st.a at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/st.fpp"
locate instance st.b at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/st.fpp"
locate instance st.c at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/st.fpp"
locate instance main.main_a at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/main.fpp"
locate instance main.b at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/main.fpp"
locate instance main.main_c at "/Users/amosalla/JPL/348C/subtopology-ac-testing/ac-tool/example/fpp-src/main.fpp"